Ci added

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,3 +1,42 @@
+# name: CI
+
+# on:
+#   push:
+#     branches:
+#       - master
+#   pull_request:
+#     branches:
+#       - master
+
+# jobs:
+#   build:
+#     runs-on: ubuntu-latest
+
+#     steps:
+#       - name: Checkout repository
+#         uses: actions/checkout@v2
+
+#       - name: Set up JDK 17
+#         uses: actions/setup-java@v2
+#         with:
+#           java-version: '17'
+#           distribution: 'temurin'
+
+#       - name: Make gradlew executable
+#         run: chmod +x googleMapScapper/gradlew
+
+#       - name: Build with Gradle
+#         run: |
+#           cd googleMapScapper
+#           ./gradlew build
+#       - name: Generate and submit dependency graph
+#         uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582    
+#         with:
+#           gradle-version: '8.8'  
+
+
+
+
 name: CI
 
 on:
@@ -23,13 +62,25 @@ jobs:
           distribution: 'temurin'
 
       - name: Make gradlew executable
-        run: chmod +x googleMapScapper/gradlew
+        run: chmod +x googleMapScrapper/gradlew
+
+      - name: Verify Gradle files exist
+        run: |
+          if [ ! -f "googleMapScrapper/build.gradle" ]; then
+            echo "Error: build.gradle file is missing."
+            exit 1
+          fi
+          if [ ! -f "googleMapScrapper/settings.gradle" ]; then
+            echo "Error: settings.gradle file is missing."
+            exit 1
+          fi
 
       - name: Build with Gradle
         run: |
-          cd googleMapScapper
+          cd googleMapScrapper
           ./gradlew build
+
       - name: Generate and submit dependency graph
         uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582    
         with:
-          gradle-version: '8.8'  
+          gradle-version: '8.8'
